# Generated by Django 5.2.4 on 2025-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.CharField(choices=[('client', 'Cliente'), ('barber', 'Barbeiro')], default='client', max_length=20),
            preserve_default=False,
        ),
    ]
