# Generated by Django 5.2.4 on 2025-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_type',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
